# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 176962a75e1871ea14719db16db9df22ebefcff7e029cb5032645b96ab45f34c3ecf4446b1302745059f6cdec96471f509f19ea1f2a6da10af8fe950b56be843

test:
  secret_key_base: 4c51d40f0b3288e556cacff406dbda4d41ec986b1b8953f1f573afc8d7c752646bce1cf72760524038f63087016d21f9829f0816d64243fb91c41fc5df5a2242

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
